# Generated by Django 4.2.10 on 2024-02-08 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='following',
        ),
        migrations.AddField(
            model_name='stream',
            name='following',
            field=models.ManyToManyField(related_name='stream_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
