# Generated by Django 4.2.10 on 2024-02-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_stream_following_stream_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
